project:
  type: website
  output-dir: docs

website:
  title: "Severity-yield relationship for white spot in maize"
  navbar:
    left:
      - href: index.qmd
        text: "About"
      - href: about.qmd
        text: "Data Analysis"
      - href: Map.qmd
        text: "Map"        

format:
  html:
    theme: Minimalist
    css: styles.css
    toc: true
    
editor: visual

