---
title: "Map"
format: html
message: false
warning: false
---

Here's the code for the map construction.

# Packages

```{r}
library(ggplot2)
library(ggthemes)
library(ggrepel)
library(ggspatial)
library(rnaturalearth)
library(rnaturalearthhires)
library(dplyr)
library(readxl)
```

# Geographic data

We’re going to upload the trial location data.

```{r}
# Geographic data
BRA <- ne_states(country = "Brazil", returnclass = "sf")

# Import data
lat_lon <- read_excel("lat_lon.xlsx")
lat_lon$lat <- as.numeric(lat_lon$lat)
lat_lon$lon <- as.numeric(lat_lon$lon)

# Define map boundaries based on coordinates
long_min <- min(lat_lon$lon, na.rm = TRUE) - 2.5
long_max <- max(lat_lon$lon, na.rm = TRUE) + 2.5
lat_min <- min(lat_lon$lat, na.rm = TRUE) - 2.5
lat_max <- max(lat_lon$lat, na.rm = TRUE) + 2.5

# Highlight selected states
highlighted_states <- c("SP", "PR", "GO", "DF")
BRA$highlight <- ifelse(BRA$postal %in% highlighted_states, "Highlighted", "Normal")

# Label adjustments
nudge_x_vals <- ifelse(lat_lon$local == "Assis Chateaubriand", -0.7, 0.5)
nudge_y_vals <- ifelse(lat_lon$local == "Assis Chateaubriand", -1, 0.7)
```

# Build the map

Here, we’re going to build the map using the `ggplot2` package.

```{r}
# Build the map
main_map <- ggplot(BRA) +
  geom_sf(aes(fill = highlight), alpha = 0.5, color = "black") +
  scale_fill_manual(values = c("Highlighted" = "grey70", "Normal" = "white"), guide = "none") +
  geom_point(data = lat_lon, aes(lon, lat, size = total_n), alpha = 0.8, color = "grey20") +
  coord_sf(xlim = c(long_min, long_max), ylim = c(lat_min, lat_max), expand = FALSE) +
  geom_label_repel(data = lat_lon,
                   aes(lon, lat, label = local),
                   size = 3,
                   nudge_x = nudge_x_vals,
                   nudge_y = nudge_y_vals,
                   fill = "white", color = "black") +
  scale_size_continuous(range = c(1, 8), guide = guide_legend(title = "Number of Trials")) +
  labs(x = "Longitude", y = "Latitude") +
  theme_bw() +
  theme(legend.position = "right", text = element_text(size = 8)) +
  annotation_scale(location = "bl", width_hint = 0.3) +
  annotation_north_arrow(location = "tl", which_north = "true",
                         style = north_arrow_fancy_orienteering()) +
  annotate("text", x = -55, y = -15.5, label = "MT", size = 3, color = "black") +
  annotate("text", x = -49.5, y = -15.5, label = "GO", size = 3, color = "black") +
  annotate("text", x = -54.6, y = -20, label = "MS", size = 3, color = "black") +
  annotate("text", x = -51.2, y = -24, label = "PR", size = 3, color = "black") +
  annotate("text", x = -54.5, y = -29, label = "RS", size = 3, color = "black") +
  annotate("text", x = -50, y = -21.5, label = "SP", size = 3, color = "black") +
  annotate("text", x = -50.5, y = -27.4, label = "SC", size = 3, color = "black") +
  annotate("text", x = -45.5, y = -18.5, label = "MG", size = 3, color = "black")
```

# Map visualization

```{r}
main_map
```
